name: life_next
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
 
  firebase_auth: ^5.2.0
 
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1

  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.4.0
  flutter_svg: ^2.0.10+1
  curved_navigation_bar: ^1.0.6
  cloud_firestore: ^5.3.0
  web: ^0.5.1
  image_picker: ^0.8.4+8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/google_icon.png
    - assets/defaultProfilePic.png

