name: life_next
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  intl: ^0.19.0
  firebase_auth: ^5.2.0
  firebase_storage: 12.2.0
  encrypt: ^5.0.1
  http: ^1.1.0
  lottie: ^2.6.0
  shared_preferences: ^2.2.2
  flutter_animate: ^4.1.1+1
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.2
  simple_animations: ^5.0.0+3
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  emoji_picker_flutter: ^1.6.2
  path: ^1.9.0
  permission_handler: ^11.3.0
  audio_waveforms: ^1.0.6
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.6
  file_picker: ^8.0.0

  flutter_polls: ^0.1.6
  share_plus: ^7.2.1

  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.4.0
  flutter_svg: ^2.0.10+1
  curved_navigation_bar: ^1.0.6
  cloud_firestore: ^5.3.0
  web: 1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/peace.png
    - assets/google_icon.png
    - assets/defaultProfilePic.png
    - assets/india.jpg
    - assets/china.jpg
    - assets/japan.jpg
    - assets/south_korea.jpg
