// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHXTqlui2n2weaMculzslHMnLFHuGi4zQ',
    appId: '1:485133518990:web:764317dfab46fb72f2e1df',
    messagingSenderId: '485133518990',
    projectId: 'durgaconnect-3081f',
    authDomain: 'durgaconnect-3081f.firebaseapp.com',
    storageBucket: 'durgaconnect-3081f.appspot.com',
    measurementId: 'G-3H7QKTT0D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpKBtYtLhGBiEFHBIGrJu9maEoRHU-iJE',
    appId: '1:485133518990:android:1f9a615331d0199ff2e1df',
    messagingSenderId: '485133518990',
    projectId: 'durgaconnect-3081f',
    storageBucket: 'durgaconnect-3081f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdesBb_paq6L5DzUhQ_avsSvnsNnj9CzY',
    appId: '1:485133518990:ios:52a51087b44b0ebff2e1df',
    messagingSenderId: '485133518990',
    projectId: 'durgaconnect-3081f',
    storageBucket: 'durgaconnect-3081f.appspot.com',
    iosClientId: '485133518990-kk63d6v3ecetq79sf1psrohsi8aen54c.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeNext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdesBb_paq6L5DzUhQ_avsSvnsNnj9CzY',
    appId: '1:485133518990:ios:52a51087b44b0ebff2e1df',
    messagingSenderId: '485133518990',
    projectId: 'durgaconnect-3081f',
    storageBucket: 'durgaconnect-3081f.appspot.com',
    iosClientId: '485133518990-kk63d6v3ecetq79sf1psrohsi8aen54c.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeNext',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHXTqlui2n2weaMculzslHMnLFHuGi4zQ',
    appId: '1:485133518990:web:8053831c4913dee0f2e1df',
    messagingSenderId: '485133518990',
    projectId: 'durgaconnect-3081f',
    authDomain: 'durgaconnect-3081f.firebaseapp.com',
    storageBucket: 'durgaconnect-3081f.appspot.com',
    measurementId: 'G-WZCJFNWH5D',
  );
}
